services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    command:
      - --copy-service
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "DevOps Sandbox Inc."
      LDAP_DOMAIN: "devops-sandbox.org"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_TLS: "false"
      LDAP_REPLICATION: "false"
    volumes:
      - ./config/ldap_sample.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
    ports:
      - "8389:389"
      - "8636:636"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "9080:80"
    depends_on:
      - openldap
